sudo: false
dist: trusty

language: java

jdk:
  - oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xms1024m -Xmx4096m -XX:PermSize=1024m"
    - JAVA_OPTS="-Xmx256m"
install:
 - mvn install

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
    - /^feature.*$/

   
notifications:
  email: false
  
notifications:
  email: false
addons:
  sonarcloud:
    organization: "diniodinev-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
