language: java
dist: focal

jdk:
  - openjdk21

env:
  global:
    - SONAR_SCANNER_OPTS="-Xmx2048m"

cache:
  directories:
    - $HOME/.gradle

branches:
  only:
    - master
    - /^feature.*$/

notifications:
  email: false

addons:
  sonarcloud:
    organization: "diniodinev-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master

script:
  - ./gradlew clean build jacocoTestReport sonarqube
