server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git :
          #uri: https://github.com/diniodinev/spring-cloud-config-repo.git
          uri: file:///C:/DinyoDinev/Projects/spring-cloud-config-repo
          search-paths: local
          
management:
  security:
    enabled: false