name: Java CI

on:
  push:
    branches:
      - master
      - 'feature*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-Xmx2048m"

      - name: Upload Gradle Problems Report (if exists)
        if: always()  # ensures it runs even if build fails
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems/problems-report.html
      - name: Print Gradle Problems Report
        if: always()
        run: |
          if [ -f build/reports/problems/problems-report.html ]; then
            echo "---- Gradle Problems Report (HTML file) ----"
            # Convert to plain text by stripping tags
            sed -e 's/<[^>]*>//g' build/reports/problems/problems-report.html | head -n 100
          else
            echo "No problems-report.html file found."
          fi
    
